[platformio]
default_envs = m5stack-cardputer

[env:m5stack-cardputer]
platform = espressif32
board = m5stack-cardputer
framework = arduino
monitor_speed = 115200
build_flags = 
    -D CORE_DEBUG_LEVEL=3
lib_deps =
    m5stack/M5Cardputer
    m5stack/M5GFX
    m5stack/M5Unified

[env:m5stack-stamps3]
platform = espressif32
board = m5stack-stamps3
framework = arduino
monitor_speed = 115200
build_flags = 
    -D CORE_DEBUG_LEVEL=3
lib_deps =
    m5stack/M5Cardputer
    m5stack/M5GFX
    m5stack/M5Unified