[env:m5stack-stamps3]
platform = espressif32 @ 6.5.0     ; Locks the Espressif toolchain platform version for stability
board = m5stack-stamps3
framework = arduino

build_flags =
    -D CORE_DEBUG_LEVEL=0          ; Completely strips debugging text strings to save internal SRAM
    -Os                            ; Optimizes compilation machine code for minimum binary footprint
    -D BOARD_HAS_PSRAM=0            ; CRITICAL: Tells the Espressif system no external PSRAM is physically present
    -D CONFIG_SPIRAM_SUPPORT=0      ; CRITICAL: Disables external memory mapping tables so they don't starve our 512KB heap
    -D ARDUINO_USB_CDC_ON_BOOT=1    ; Enforces valid native USB monitor tracking on power-up

lib_deps =
    m5stack/M5Cardputer >= 1.0.3   ; Locks the minimum required keyboard layout version
    m5stack/M5GFX >= 0.2.28         ; Locks the minimum required 8-bit color canvas features

monitor_speed = 115200
upload_speed = 1500000              ; Rapid deployment flash clock transmission pace