[platformio]
default_envs = m5stack-cardputer

[env:m5stack-cardputer]
platform = espressif32
board = m5stack-cardputer
framework = arduino
monitor_speed = 115200

; 🧼 TRACE RE-ALIGNMENTS: NO MORE "-w" CRUTCHES
build_flags = 
    -D CORE_DEBUG_LEVEL=3

; 📦 RE-ALIGNED PACKAGES WITHOUT SPACING TYPOS
lib_deps =
    m5stack/M5Cardputer
    m5stack/M5GFX
    m5stack/M5Unified
    adafruit/Adafruit_NeoPixel